---
application_name: Takeoff App
business_name: Jack Company
business_address: 
domain: example.com
support_email: jp3stephens@gmail.com
default_from_email: My App <no-reply@example.com>
background_job_processor: async
email_provider: 
personal_accounts: true
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
